format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics"""

# Inserts a blank line between shell prompts
add_newline = false

[character] # The name of the module we are configuring is "character"
disabled = true # Disable the symbol
error_symbol = "[λ](bold #E64E4C)"
success_symbol = "[λ](bold #98E481)"

[directory]
style="#037BA6"
read_only = " "
truncate_to_repo=false
truncation_length = 4
truncation_symbol = "…/"
repo_root_style="bold #037BA6"

[git_branch]
# symbol = ' '
format='on [$symbol$branch]($style) '
# truncation_length = 10
truncation_symbol = '...'
style='bold #038082'
# ignore_branches=[]

[git_metrics]
# disabled=false
# added_style='green'
# deleted_style='red'
# format='([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_state]
style='#038082'

[git_status]
style='#038082'
# format='([\[$all_status$ahead_behind\]]($style) )'
ahead = '[⇡](bold #038082)${count}'
conflicted = '[=](bold #038082)${count}'
diverged = '[⇕⇡](bold #038082)${ahead_count}⇣${behind_count}'
behind = '[⇣](bold #038082)${count}'
modified = '[!](bold #038082)${count}'
untracked = '[?](bold #038082)${count}'
stashed = '[\\$](bold #038082)${count}'
staged = '[+](bold #038082)${count}'
renamed = '[»](bold #038082)${count}'
deleted = '[✘](bold #038082)${count}'

[nodejs]
symbol=' '
style='bold #8AFF66'

[ruby]
# format='| [$symbol($version )]($style)'
# symbol='Ruby '
style='bold #E74340'
