format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics"""

# Inserts a blank line between shell prompts
add_newline = false

[character] # The name of the module we are configuring is "character"
disabled = true # Disable the symbol
error_symbol = "[λ](bold #E64E4C)"
success_symbol = "[λ](bold #98E481)"

[directory]
style="#26AAD9"
read_only = " "
truncate_to_repo=false
truncation_length = 4
truncation_symbol = "…/"
repo_root_style="bold #26AAD9"

[git_branch]
# symbol = ' '
format='on [$symbol$branch]($style) '
# truncation_length = 10
truncation_symbol = '...'
style='bold #26D6D9'
# ignore_branches=[]

[git_metrics]
# disabled=false
# added_style='green'
# deleted_style='red'
# format='([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_state]
style='#26D6D9'

[git_status]
style='#26D6D9'
# format='([\[$all_status$ahead_behind\]]($style) )'
ahead = '[⇡](bold #26D6D9)${count}'
conflicted = '[=](bold #26D6D9)${count}'
diverged = '[⇕⇡](bold #26D6D9)${ahead_count}⇣${behind_count}'
behind = '[⇣](bold #26D6D9)${count}'
modified = '[!](bold #26D6D9)${count}'
untracked = '[?](bold #26D6D9)${count}'
stashed = '[\\$](bold #26D6D9)${count}'
staged = '[+](bold #26D6D9)${count}'
renamed = '[»](bold #26D6D9)${count}'
deleted = '[✘](bold #26D6D9)${count}'

[nodejs]
symbol=' '
style='bold #8AFF66'

[ruby]
# format='| [$symbol($version )]($style)'
# symbol='Ruby '
style='bold #FF6866'
